
export class CommonConstants{

  static readonly  SEARCH_WEIGHT:number = 10

  static readonly DIVIDER_STROKE_WIDTH:number = 1

  static readonly DETAIL_LIST_OFFSET_LG:number = 1

  static readonly DETAIL_LIST_SPAN_LG:number = 9

  static readonly DETAIL_LIST_SPAN_SM:number = 3

  static readonly SIDE_LIST_SPAN_SM:number = 1

  static readonly SIDE_LIST_SPAN_MD :number = 2

  static readonly SIDE_LIST_SPAN_LG:number = 2

  static readonly TOP_SPAN_LG:number = 12

  static readonly TOP_SPAN_MD:number = 8

  static readonly TOP_SPAN_SM:number = 4

  static readonly COLUMN_LG:number = 12

  static readonly COLUMN_MD:number = 8

  static readonly COLUMN_SM:number = 4

  static readonly GRID_COLUMNS_GAP_NORMAL:number = 24

  static readonly GRID_COLUMNS_GAP_SM:number = 12

  static readonly GUTTER_X:number = vp2px(24)

  static readonly BREAK_POINTS_VALUE:Array<string> = ['320vp','600vp','840vp']

  static readonly GRID_TEMPLATE_THREE:string = '1fr 1fr 1fr'

  static readonly GRID_TEMPLATE_TWO:string = '1fr 1fr'

  static readonly BREAK_POINT_SM:string = 'sm'

  static readonly SEARCH_PLACEHOLDER:string = 'Search..'

  static readonly SEARCH_FONT_FAMILY:string = 'serif'

  static readonly INDEX_LIST_FONT_WEIGHT:number = 400

  static readonly LIST_SIZE:number = 6

  static readonly DETAIL_LIST_FONT_WEIGHT:number = 500

  static readonly TAB_ITEM_FONT_WEIGHT:number = 500

  static readonly TAB_BAR_SIZE:number = 5

  static readonly TAB_LAYOUT_WEIGHT:number = 1

  static readonly TITLE_FONT_WEIGHT:number = 500

  static readonly SUBTITLE_FONT_WEIGHT:number = 400

  static readonly DETAIL_ITEM_SIZE :number = 6

  static readonly FULL_WIDTH_PERCENT:string = '100%'

  static readonly FULL_HEIGHT_PERCENT:string = '100%'

  static readonly HALF_HEIGHT_PERCENT:string = '50%'

  /**
   * 设备UUID
   */
  static readonly UUID = '3e7ee30c6fc0004a773dc33b0597b5732b145c04'

  /**
   * 设备号
   * @type {string}
   */
  static readonly DEVICE_NUM = "ONEPLUS%20A6000"


}